services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_backend
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - '6379:6379'

volumes:
  mongo_data:
